### ISSUE TITLE
Controller structure

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#11]
Does it make sense to have separate controllers for Admin and Teacher for the UI? (https://xd.adobe.com/view/d8a50ef1-51f1-40da-9588-874151c18c0e/)

Most of the views are going to be very similar between the two roles, and should inherit anyway.

**Comment by simonjduff** [comment]
Absolutely yes, keep them separate. If there are shared UI elements, that's what the _Shared view folder is for

**Comment by jaduff** [comment]
Ok,ta
