### ISSUE TITLE
Capturing form data

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#15]
How do you get form data from POST into the controller? There is very little consistency in search results, across lots of different versions of ASP. I want to capture Name from the AddRoom form.

**Comment by simonjduff** [comment]
This is called Model Binding. Create a class that serializes to/from your form data and make it the parameter of your controller action.
Eg
    `public IActionResult Login(LoginMessage login){}`

    public class LoginMessage
    {
        public string Username{get;set;}
        public string Password{get;set;}
    }

**Comment by jaduff** [comment]
Can't use the existing Room.cs class for the purpose?

**Comment by simonjduff** [comment]
You can do what you want, I just sketched an example :)

**Comment by jaduff** [comment]
I tried to use the existing Room.cs and it didn't work, Name was Null, using the RoomModel.cs that I'd created earlier works fine. But I don't know why.
