### ISSUE TITLE
Namespaces vs folders

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#17]
By moving EntityTests, and Steps into a new folder called Write Tests, does this alter the Namespace?
I tried it, and it seemed not to. But then what happens with Read Tests? Doesn't this create a risk of conflicting names?

**Comment by jaduff** [comment]
Ah, the namespace is declared in the source file that you're referring to :)

**Comment by jaduff** [comment]
Hmm, except I can't have mirrored folder structures in different parent folders. It complains that it conflicts with an existing folder, even though its not in the same location.

**Comment by simonjduff** [comment]
The namespace aren't automatically changed, you'll need to do this manually. In Visual Studio 2017 there's a tool called Resharper, or a full IDE by the came company called Rider, that does this kind of refactoring automatically. VS Code doesn't have this kind of power.
