### ISSUE TITLE
'Deleting' labs

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#22]
Should labs actually be deleted?
Or marked as disabled?
Assuming the later, what is the best way to implement? Add a boolean property?
Can a room be undeleted?
What happens to the machines in a room?
Can there be a 'room' called 'unassigned', which contains the machines that have no room? This room wouldn't show up on the room list, but the machines could be accessible through another means.

**Comment by simonjduff** [comment]
Is a lab a room, or something else? If it's a room, why have two names?
Using the real world model, you can only delete a room by bulldozing it. So yes, you can delete it, but only if you really, really mean it.

**Comment by jaduff** [comment]
Yes a lab is a room. Lab is a subset of room in the real world. But this program LabLog is only going to handle Computer Labs.
I can delete a room from this context, by removing all computers from it, and calling it a standard classroom. But your point is taken. The computers don't need to keep their events if they are moved from one room to another, because the damage logs are contextual to the room. It matters which room the damage was done in, and then which computer.
