### ISSUE TITLE
Why is ComputerId an int, instead of a guid?

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#27]
A computer is unique. It exists only in one place at a time. It may be moved from one room to another, but if it exists in two rooms, it is in error.
Given the structure of the domain with room as aggregate, could/should computerid be a guid?

**Comment by simonjduff** [comment]
Because you said they have  numbers, no other reason

**Comment by jaduff** [comment]
either guid, or serial number would be more useful as unique identifier. If a machine were to be moved, it is the machine that the damage and usage history sticks with, not the position number. I probably said I wouldn't move computers, but I know other schools do routinely.

**Comment by simonjduff** [comment]
Change it :)
