### ISSUE TITLE
How to handle images in source control?

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#3]
What is the recommended way to handle images in git during development?
I'll need to have a gui with a large image. Does this get uploaded into git?
Or should it be hosted externally and linked to?

**Comment by simonjduff** [comment]
Consensus seems to be that for small numbers of small images, it's ok to put them into git.
If you've got massive PSD files used to generate assets, they should go elsewhere.

**Comment by jaduff** [comment]
Done.
