### ISSUE TITLE
eventHandler in School.cs - conflicting requirements

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#33]
I've run into a problem with eventHandler in School.cs in the domain.
In testing, you pass requirements down the chain with given, then, etc.
When replaying events outside of the testing environment, I create a school, and pass it a list of previous events (including the school creation event itself) so that it is current.
Then, I call `school.AddRoom` (as an example). AddRoom will create the AddRoomEvent and forward it to the event handler in the same way that the School.Create method does.
```
public void AddRoom(string roomName, Action<ILabEvent> eventHandler)
        {
            _eventHandler = eventHandler;

            var @event = LabEvent.Create(
                Guid.NewGuid(),
                ++Version,
                new RoomAddedEvent(roomName));
            _eventHandler(@event);
        }
```

 However, this requires an event handler. And the event handler for AddRoom will be different to Create.
So when I run school.AddRoom, I need to pass it the information for the Room, as well as an event handler. I changed the event handler from read only, to private, so I can change it after the school is created.
```
Domain.Entities.School school = new Domain.Entities.School(id, eventList, e =>
                {
                    e.EventAuthor = _user;
                    _db.Add(e);

                    SchoolModel schoolModel = _db.Schools.Where(w => (w.Id == id)).SingleOrDefault();
                    schoolModel.ApplyRoomAddedEvent(e);
                });
```
But this all broke the test mechanism, which doesn't pass an event handler in the testing chain.
How should I handle the other events (like AddRoom, AddComputer, etc) without passing a new event handler after school creation? Or alternatively, how do I handle testing once I require an event handler?

**Comment by jaduff** [comment]
It felt somewhat like chasing down a rabbit hole. Less spaghetti code, more rabbit warren.

**Comment by simonjduff** [comment]
"However, this requires an event handler. And the event handler for AddRoom will be different to Create.".
This doesn't sound right to me at all. The event handler should be the same for all events, ie - save the event to the database

**Comment by jaduff** [comment]
Yeah, but, I was using the event to also modify the read model. So the domain would return an event to the event handler, which would then be used to update the read model. The advantage of this is that if I have to rebuild the read model from the events, then the code that already exists can be used.
The alternative is manually updating the read model when the event is created, and then having a separate ApplyEvent code to update the read model from the database during a rebuild.

**Comment by jaduff** [comment]
So the event that is returned goes straight to an ApplyEvent method in the read model, updating it as it goes. When I replay the events later to rebuild the read model for consistency, I just send the events to the same methods.
And because this is how the read model was updated in the first place, I can be confident that the result will be the same in a replay situation. If I just save form data, I can't be sure the read and write models have the same data.

**Comment by jaduff** [comment]
Hmm, I suppose I could direct the event handler to send the data to a replayevent method in the read model, which would then interpret the event type and process it appropriately.

**Comment by jaduff** [comment]
See PR #34

**Comment by jaduff** [comment]
I can't tell if I've rubber duckyed you, or if you have cunningly led me to a solution.
Or, alternatively, if my solution isn't a good idea at all ;.;
