### ISSUE TITLE
Tracking private properties in database

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#38]
I want to track _latestVersion from SchoolModel in the database. It should only be accessed from inside the object itself, but should persist.
I found https://romiller.com/2012/10/01/mapping-to-private-properties-with-code-first/ which shows how to achieve this in EF6, but is broken in EF Core.
Any suggestions on how to track a private property in EF Core?

**Comment by simonjduff** [comment]
Don't bother. You're the only developer, the code won't be shared. Tag it with [Obsolete] to generate a warning if you like.

**Comment by jaduff** [comment]
Ok done :)
