### ISSUE TITLE
No name in Room class for LabLog.domain

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#6]
Need to add the ability to give a name to the room before the event is saved.

**Comment by jaduff** [comment]
Testing incomplete. Can't test for the Room Name in the event, as it is stored in the Event Body rather than the event itself. How do you test for it?
Have partially implemented but commented out.

**Comment by simonjduff** [comment]
Assert against the event body. You'll need to cast ILabEvent back to
LabEvent<T> first. Or you could deserialize EventBody and then assert

**Comment by jaduff** [comment]
How do I cast ILabEvent back to LabEvent? And then what do I do with it?

**Comment by jaduff** [comment]
PR merged, issue closed.
