### ISSUE TITLE
What is the primary key of an event?

### ISSUE THREAD

**Issue by jaduff** [jaduff/LabLog#8]
Events have a Guid roomid, and a timestamp. But what is the primary key? There is no guid eventid?

Additionally, should all events be stored in a single table, or should roomcreated, computeradded, etc be separate tables of similar events?

Presumably they should all be in the one place for easy replaying. But implementing this is made difficult as the DbContext needs access to a non-generic type. LabEvent is generic and doesn't seem to be able to be used for this purpose.

**Comment by simonjduff** [comment]
Key is compound {RoomId, Version}.
We haven't built version yet, I'll show you that today. All events go in the same table
